# pandas.errors.OutOfBoundsTimedelta

exceptionpandas.errors.OutOfBoundsTimedelta

    
Raised when encountering a timedelta value that cannot be represented as a
timedelta64[ns].

© 2008–2022, AQR Capital Management, LLC, Lambda Foundry, Inc. and PyData
Development Team  
Licensed under the 3-clause BSD License.  
https://pandas.pydata.org/pandas-
docs/version/1.4.0/reference/api/pandas.errors.OutOfBoundsTimedelta.html

